title: Maxwell Conte
author: Maxwell Conte
description: Student at the Carol Martin Gatton Academy of Mathematics and Science in Kentucky and Western Kentucky University.

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
