title: Maxwell Conte
tagline: 
lang: en
author:
  name: Maxwell Conte
  url: 
tags_path: /tags/
categories_path: /categories/

disqus: 
google_analytics: 

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
