# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Maxwell
tagline:             'Conte'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon/'
paginate:            5
encoding: UTF-8

# About/contact
author:
  name:              Maxwell Conte
  url:               Testing
  email:             maxwell dot conte at gmail.com

# Custom vars
version:             1.0.0
