# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Maxwell Conte
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon/'
paginate:            5

# About/contact
author:
  name:              Maxwell Conte
  url:               maxwell-conte.github.io  
  email:             maxwell [dot] conte [at] gmail [dot] com
# Custom vars
version:             1.0.0
